### ISSUE TITLE
i cant inject the hack

### ISSUE THREAD

**Issue by Britishkun** [lnx00/Fedoraloader#3]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.get_Handle()
   at Fedoraloader.MainWindow.Inject(Process pProcess, String pFileName)
   at Fedoraloader.MainWindow.RunLoader()
   at Fedoraloader.MainWindow.<btnLoad_Click>b__8_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Fedoraloader.MainWindow.btnLoad_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by lnx00** [comment]
Did you run Fedoraloader as administrator?

**Comment by Britishkun** [comment]
yes

**Comment by lnx00** [comment]
And you didn't start TF2 as administrator?

**Comment by Britishkun** [comment]
https://i.imgur.com/TEV7AbA.png
how do i start

**Comment by lnx00** [comment]
You don't, that's the thing. Just start Steam and TF2 regular. Something is preventing Fedoraloader from accessing the game process on your computer. Maybe some antivirus, or insufficient permissions.

**Comment by Britishkun** [comment]
i dont using any antivuris program or win def

**Comment by lnx00** [comment]
Then I sadly don't have any solution for you. The loader seems to be working fine for everyone else and the only hint that the Exception Text is giving me is, that the access to the game process was denied while injecting (or while opening the process handle to be more specific).
